version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo-db-books-container
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: mongod --port ${DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongo_books_data:/data/db
    networks:
      - redis-mongo-books-network
  redis:
    image: redis
    container_name: redis_cache_books
    expose:
      - 6379
    networks:
      - redis-mongo-books-network
  app_books:
    container_name: books_app
    build: ./
    env_file: .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_HOST: mongo-db-books-container
      REDIS_URL: redis://redis_cache_books
      NODE_ENV: development
      PORT: ${PORT}
    networks:
      - redis-mongo-books-network
    command:
      sh -c 'npm i && node ./dist/index.js'
volumes:
  mongo_books_data:
networks:
  redis-mongo-books-network:
    driver: bridge